name: Cargo lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    name: Marinade Common RS CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features